### ISSUE TITLE
Apply Palette using vt.color kernel parameter???

### ISSUE THREAD

**Issue by inkstray** [CallMeEchoCodes/tty#4]
### Is this possible?

**Comment by CallMeEchoCodes** [comment]
I have another project im working on right now but when im done with that ill have a look into this. If you could send over some docs for the parameter that would be great

**Comment by sophuric** [comment]
https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html

it seems `vt.color` is just the default color, so `vtcolor=0x0f` for example will put a black (0) background and a white (f) foreground, but it seems `vt.default_red` `vt.default_grn` and `vt.default_blu` can let you change the default palette, it seems that they are listed as a list of all red values, a list of all green values, and a list of all blue values, instead of a list of the colors in rgb

the default colors are listed here: https://github.com/torvalds/linux/blob/49572d5361298711207ab387a6c318407deb963a/drivers/tty/vt/vt.c#L1380

I will make a fork with the colours, do I override setting it in /etc/issue, or do I keep that?

**Comment by CallMeEchoCodes** [comment]
This is almost done and will be merged soon :)

**Comment by CallMeEchoCodes** [comment]
fixed by #5
